:: Copyright © 2013-2020 Graphia Technologies Ltd.
::
:: This file is part of Graphia.
::
:: Graphia is free software: you can redistribute it and/or modify
:: it under the terms of the GNU General Public License as published by
:: the Free Software Foundation, either version 3 of the License, or
:: (at your option) any later version.
::
:: Graphia is distributed in the hope that it will be useful,
:: but WITHOUT ANY WARRANTY; without even the implied warranty of
:: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
:: GNU General Public License for more details.
::
:: You should have received a copy of the GNU General Public License
:: along with Graphia.  If not, see <http://www.gnu.org/licenses/>.

@echo off
setlocal EnableDelayedExpansion

call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
set PATH=%PATH%;C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin;C:\Qt\Qt5.14.2\Tools\QtCreator\bin;C:\Program Files (x86)\NSIS\Bin
set CRTDIRECTORY=%VcToolsRedistDir%\x64\Microsoft.VC142.CRT

:: The contents of WINDOWS_SIGN_KEYSTORE_BASE64 can be generated by:
:: certutil -encodehex <p12/pfx file> output.txt 0x40000001

echo %WINDOWS_SIGN_KEYSTORE_BASE64% > encoded-keystore.txt
set WINDOWS_SIGN_KEYSTORE=keystore.p12

certutil -decode encoded-keystore.txt %WINDOWS_SIGN_KEYSTORE%
certutil -p %WINDOWS_SIGN_PASSWORD% -dump %WINDOWS_SIGN_KEYSTORE%
certutil -p %WINDOWS_SIGN_PASSWORD% -importPFX %WINDOWS_SIGN_KEYSTORE%
del encoded-keystore.txt %WINDOWS_SIGN_KEYSTORE%

call "scripts\windows-build.bat"
call "installers\windows\build.bat"
